spring.application.name=api

# PUERTO Y CONTEXTO DEL SERVIDOR
server.port=8080
server.servlet.context-path=/api/v1

# CONEXION A SUPABASE
spring.datasource.url=jdbc:postgresql://db.bwckxakkoghtqqwxunpd.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Liceo2009W3b}
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION JPA (para que hibernate funcione correctamente)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CONFIGURACION DE JWT
jwt.secret=${JWT_SECRET:7f9a2b4c6d8e0f1a3b5c7d9e2f4a8b1c3d5e7f9a2b4c6d8e0f1a3b5c7d9e2f4a}
jwt.expiration=${JWT_EXPIRATION:86400000}